#!/usr/bin/perl
use strict;
use warnings;
use UI::Bowdlator::Filter;
use Encode::Arabic::Franco;
use open ':std', ':encoding(UTF-8)';
use utf8;

print "$0 starting..\n";
my $bowdlator = UI::Bowdlator::Filter->new()
    or die "Bowdlator server not online\n";

my $composed = '';
while ($bowdlator->getKey(handle_backspace => \$composed)) {

    if (/^[^[:graph:]]/a) { # non graphical character ends composition
        if ($composed =~ /^[`§]|[§`]$/) {
            $composed =~ s/[§`]//g;
        } else {
            print "input: $composed\t";
            $composed =~ s/-/ـ/g; # ta6weel
            $composed = decode "franco-arabic", $composed;
        }

        print "committed: $composed\n";
        $bowdlator->commit(\$composed);
        next;
    }

    $composed .= $_;

    $bowdlator->suggest($composed);
}
